<a href="https://colab.research.google.com/github/ItsTheGraveWalker/jelonx/blob/master/Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Welcome to the Python Basics</h1>

<p>This will cover the basics of Python. The goal is to get people comfortable using Python. It also will cover how to use popular data science libraries like

<ul>
    <li>Pandas</li>
    <li>Numpy</li>
</ul>


</p>

<h1>Introduction into Python</h1>

<h2>Syntax and Algorithmic Thinking</h2>

Lets take a look at the Python Syntax 

In [0]:
def unscrew(spread):
    print('Unscrewing {}.'.format(spread))

def getPlate():
    print("Placing plate on table.")

def openBread():
    print('Opening Bread')
    
def getSlice():
    print('Heres a slice.')
    return 'Slice'
    
def getSpread(spread):
    print('Yum {}'.format(spread))
    return spread
    
def spreading(slice,knife):
    print("Putting {0} on the {1}.".format(knife,slice))
    return knife
    
def combine(halves):
    print('Putting {} half on {} half!'.format(halves[0],halves[1]))

def placeOnPlate():
    print("Putting it on the Plate")
    
def makePBAndJ(): # def is used to make a function

    spreads = ['Peanut Butter', 'Jelly'] # Create a list of spreads
    
    for spread in spreads: # Go through the list
        unscrew(spread) # Call function unscrew on spread
    
    getPlate() # Call get the plate
    
    halves = [] # Create an empty list
   
    openBread()
    
    for spread in spreads: # Go through the spreads

        slice = getSlice() # Get a slice of bread
        
        knife = getSpread(spread) # Get spread on knife
        
        halves.append(spreading(slice,knife)) # add prepared half to our half list
    
    combine(halves) # Combine the halves together
    placeOnPlate()
    
    
def sillyMan():
    
    makePBAndJ()
    
    print('\n....Now how do I eat it?')

sillyMan() 

Unscrewing Peanut Butter.
Unscrewing Jelly.
Placing plate on table.
Opening Bread
Heres a slice.
Yum Peanut Butter
Putting Peanut Butter on the Slice.
Heres a slice.
Yum Jelly
Putting Jelly on the Slice.
Putting Peanut Butter half on Jelly half!
Putting it on the Plate

....Now how do I eat it?


<h2>Getting user input</h2>

How can I get the user to give me information. Python has a function called input and with input we can save it to a variable.

In [0]:
name = input("Please enter your name ")
print("Hello " + name + " welcome to Python Basics")

Please enter your name Sam
Hello Sam welcome to Python with data science


Remember this section above since we will use the input function. 

<h1>Variables</h1>
<p>Variabe do not need to be defined before executing them. All you need to do is name the variable</p>

In [0]:
test_variable = 1234
type(test_variable)

int

<p> 
    Variables can have the following types:
    
    
<li>String</li>
<li>Number</li>
<li>List</li>
<li>Tuple</li>
<li>Dictionary</li>
    
    
</p>

<h3>String variables</h3>

In [0]:
test_string_variable = "Hello World!"

In [0]:
type(test_string_variable)

str

In [0]:
test_string_variable = "Hello*******,World              \n"

In [0]:
test_string_variable.strip()

'Hello*******,World'

In [0]:
test_string_variable.replace('*','')

'Hello,World              \n'

In [0]:
test_string_variable = test_string_variable.replace('*','').strip()
test_string_variable

'Hello,World'

In [0]:
test_string_variable.split(',')

['Hello', 'World']

<h4>Concating Strings</h4>
<p>We can also concate or combining strings together</p>

In [0]:
#Concat
first_name = "Daniel"
last_name = "Wright"
print(first_name + " " + last_name)

Daniel Wright


<h4>Escaping characters</h4>
<p>You saw how the Double Quotes were not printed. This is because this is used to write a string. However we can still printout double quotes if we choose too. </p>

In [0]:
#Escape characters
print("\"If you are going to through hell, keep going\", Winston Churchill")

"If you are going to through hell, keep going", Winston Churchill


The "\" backslash character allowed us to escape the double quote. This can be done for other things such as tabs. This escape character allows us to be able to print out information in the correct way we want. 

<h4>Replacement fields</h4>

<p>Replacement fields are a feature of Python 3, this allows us to do multiple concatenations</p>

Not needed

In [0]:
# Notice how .format is inside the print function 
print("Hello {1} {0}. Welcome to the website".format("Francisco","Quintana")) 

Hello Quintana Francisco. Welcome to the website


In [0]:
# We do not always need to have it has {0} the value inside the bracket can be empty such as {}. 
# Then it will follow the normal method
print("Hello {} {}. Welcome to the website".format("Francisco","Quintana"))

Hello Francisco Quintana. Welcome to the website


<h4>Slicing strings</h4>
String are a sequence of characters. This means we can access a individual character or characters by slicing the string

In [0]:
string = "The quick brown fox"
print(string[4])

q


<p>Why "q" why not a " " white space, remember white spaces are also characters. And that is because everything in Python is zero index. So the "T" in "The" is actually position 0 and not position 1 </p>

In [0]:
string[10:]

'brown fox'

<h1>Lists</h1>
Lists in Python are a common data structures with some similarity to Numpy arrays. 

In [0]:
colors = ["Red","Blue","Green"]

In [0]:
colors_two = ["Yellow","Purple","Orange"]
colors.extend(colors_two)

In [0]:
colors

['Red', 'Blue', 'Green', 'Yellow', 'Purple', 'Orange']

Removing elements from a list.
Pop needs integer, while remove takes element

In [0]:
colors.pop(1)
colors

['Red', 'Green', 'Yellow', 'Purple', 'Orange']

In [0]:
colors.pop()
colors

['Red', 'Green', 'Yellow', 'Purple']

In [0]:
colors.remove('Yellow')
colors

['Red', 'Green', 'Purple']

Removing elements from a list using pop()

In [0]:
colors.count('Red')

1

In [0]:
colors.sort()
colors

['Green', 'Purple', 'Red']

In [0]:
colors.reverse()
colors

['Red', 'Purple', 'Green']

In [0]:
colors.insert(0,'Yellow')
colors

['Yellow', 'Red', 'Purple', 'Green']

Illustrating the differences between saving a copy by variable and creating a copy

In [0]:
colors2 = colors

In [0]:
colors.append('White')
print('This is colors: {}'.format(colors))
print('This is colors2: {}'.format(colors2))

This is colors: ['Yellow', 'Red', 'Purple', 'Green', 'White']
This is colors2: ['Yellow', 'Red', 'Purple', 'Green', 'White']


In [0]:
colors3 = colors.copy() # Return a shallow copy

In [0]:
colors3

['Yellow', 'Red', 'Purple', 'Green', 'White']

In [0]:
colors.append('Brown')
print('This is colors: {}'.format(colors))
print('This is colors3: {}'.format(colors3))

This is colors: ['Yellow', 'Red', 'Purple', 'Green', 'White', 'Brown']
This is colors3: ['Yellow', 'Red', 'Purple', 'Green', 'White']


Notice how we now append the value "Rainbow" to the colors2 list.  And it updates colors as well. 

In [0]:
colors2.append("Rainbow") 

In [0]:
colors2

In [0]:
colors

In [0]:
colors3 # But colors 3 does not get upadated

In [0]:
colors3.append("Black")

In [0]:
colors3

In [0]:
colors3.clear()
colors3

[]

<h2>Tuples</h2>

Tuples are similar to lists except they cannot be changed. 

In [0]:
positive = "Red","Green","Blue"
negative = ("Cyan","Magenta","Yellow")

In [0]:
type(positive)

tuple

In [0]:
type(negative)

tuple

Elements in tuples are immutable

In [0]:
negative[0] = 'Yellow'

TypeError: 'tuple' object does not support item assignment

In [0]:
list(negative)

['Cyan', 'Magenta', 'Yellow']

Below is a example of unpacking a tuple

In [0]:
user_data = ("Daniel","Wright","M","20/02/1981")
first_name,last_name,gender,dob = user_data

In [0]:
print("My name is {0} {1} and I am a {2}ale and born on {3}".format(first_name,last_name,gender,dob))

My name is Daniel Wright and I am a Male and born on 20/02/1981


<h2>Dictionaries</h2>

A dictionary is a data type that is a unordered sequence that is a key value pair

In [0]:
movies = {
    
    'name': 'City of god',
    'year':2002,
    'genre':'Drama',
    'language':'Portuguese',
    'imdb':8.6
}

In [0]:
movies

{'name': 'City of god',
 'year': 2002,
 'genre': 'Drama',
 'language': 'Portuguese',
 'imdb': 8.6}

In [0]:
type(movies)

dict

<h3>Deleting a dictionary</h3>

<p>You can delete a value from a dictionary. This helps you remove a element from the dictionary</p>

In [0]:
del movies["imdb"]
print(movies)

{'name': 'City of god', 'year': 2002, 'genre': 'Drama', 'language': 'Portuguese'}


<h3>Adding a element to a dictionary</h3>
You can add a element to a dictionary

In [0]:
movies["imdb"] = 8.6
movies

{'name': 'City of god',
 'year': 2002,
 'genre': 'Drama',
 'language': 'Portuguese',
 'imdb': 8.6}

In [0]:
movies

{'name': 'City of god',
 'year': 2002,
 'genre': 'Drama',
 'language': 'Portuguese',
 'imdb': 8.6}

<h3>Combing dictionaries</h3>
<p>You can combine dictionaries together using the following method</p>

In [0]:
cast_info = {'cast': 
{
 "Rocket":"Alexandre Rodrigues",
 "Lil Ze":"Leanardo Firmino",
 "Benny": "Phellipe Haagensen"
}
}

In [0]:
cast_info

{'cast': {'Rocket': 'Alexandre Rodrigues',
  'Lil Ze': 'Leanardo Firmino',
  'Benny': 'Phellipe Haagensen'}}

In [0]:
movies.update(cast_info)

In [0]:
movies

{'name': 'City of god',
 'year': 2002,
 'genre': 'Drama',
 'language': 'Portuguese',
 'imdb': 8.6,
 'cast': {'Rocket': 'Alexandre Rodrigues',
  'Lil Ze': 'Leanardo Firmino',
  'Benny': 'Phellipe Haagensen'}}

We saw above how we can update a dictionary with the value of another one. But what happens when we enter a dictionary with the same key

In [0]:
new_name = {'name':"Ciudad de Dios"}

In [0]:
movies.update(new_name)

In [0]:
movies

{'name': 'Ciudad de Dios',
 'year': 2002,
 'genre': 'Drama',
 'language': 'Portuguese',
 'imdb': 8.6,
 'cast': {'Rocket': 'Alexandre Rodrigues',
  'Lil Ze': 'Leanardo Firmino',
  'Benny': 'Phellipe Haagensen'}}

<h2>Messing around with dictionaries</h2>

In [0]:
movie_keys = movies.keys()

In [0]:
movie_keys

dict_keys(['name', 'year', 'genre', 'language', 'imdb', 'cast'])

In [0]:
movies.values()

dict_values(['Ciudad de Dios', 2002, 'Drama', 'Portuguese', 8.6, {'Rocket': 'Alexandre Rodrigues', 'Lil Ze': 'Leanardo Firmino', 'Benny': 'Phellipe Haagensen'}])

In [0]:
#Making a tuple into a dict
movie_tuple = movies.items()
print(movie_tuple)

dict_items([('name', 'Ciudad de Dios'), ('year', 2002), ('genre', 'Drama'), ('language', 'Portuguese'), ('imdb', 8.6), ('cast', {'Rocket': 'Alexandre Rodrigues', 'Lil Ze': 'Leanardo Firmino', 'Benny': 'Phellipe Haagensen'})])


Out of order

In [0]:
#Iterating through dictionaries example one
for key,values in movies.items():
    print("The key is {0} and the value is {1}".format(key,values))

The key is name and the value is Ciudad de Dios
The key is year and the value is 2002
The key is genre and the value is Drama
The key is language and the value is Portuguese
The key is imdb and the value is 8.6
The key is cast and the value is {'Rocket': 'Alexandre Rodrigues', 'Lil Ze': 'Leanardo Firmino', 'Benny': 'Phellipe Haagensen'}


In [0]:
#Iterating through dictionaries example two
for key in movies:
    print(key,movies[key])

name Ciudad de Dios
year 2002
genre Drama
language Portuguese
imdb 8.6
cast {'Rocket': 'Alexandre Rodrigues', 'Lil Ze': 'Leanardo Firmino', 'Benny': 'Phellipe Haagensen'}


<h1>Sets</h1>
<p>Sets are unsorted sequence with no duplications and no keys</p>

In [0]:
primes = {2,3,5,7,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,13,17,19}
primes

{2, 3, 5, 7, 11, 13, 17, 19}

In [0]:
type(primes)

set

# Casting<br>
Of all the types we see you can cast to other types within reason

In [0]:
list(primes)

[2, 3, 5, 7, 11, 13, 17, 19]

In [0]:
dict(zip(primes,primes))

{2: 2, 3: 3, 5: 5, 7: 7, 11: 11, 13: 13, 17: 17, 19: 19}

In [0]:
tuple(primes)

(2, 3, 5, 7, 11, 13, 17, 19)

In [0]:
num = list(primes)[0]
num

2

In [0]:
str(num)

'2'

<h1>Control Flow</h1>
<p>Control flow allows us to control when a program executes. It lets us test a condition and then execute a block of code</p>

In [0]:
# Operators
a = 4
b = 5
c = 6
d = True
e = False


bool1 = d and ( a > b )
print(bool1)

bool2 = ( not d ) or ( b != c )
print(bool2)

bool3 = ( d and ( not e ) ) or ( a > b )
print(bool3)

bool4 = ( 4 + 5 ==  9 ) and ( ( not d ) or e ) 
print(bool4)

False
True
True
False


In [0]:
# Control Flow

def mood(weather):
    weather = weather.lower()
    if weather == 'sunny':
        print('Yay!')
    elif weather == 'snowing':
        print('Boo')
    else:
        print('I don\'t care')
        
weather = input('What is the weather outside? ')

mood(weather)

What is the weather outside? tornado
I don't care


<h1>Looping</h1>
<p>There are two main type of loops for and while loops.</p>
<h3>For Loops</h3>
<p>For loops work by iterating through element N times</p>

In [0]:
for n in range(0,10):
    print("n is now {0}".format(n))

n is now 0
n is now 1
n is now 2
n is now 3
n is now 4
n is now 5
n is now 6
n is now 7
n is now 8
n is now 9


<p>We now will iterate through any element N times. For loops will always stop when they reach the end of the loop based by the range</p>

<h3>While Loops</h3>
<p>While loops iterate through elements until the condition is meant</p>

In [0]:
i = 0
while i < 10:
    print("i is now {0}".format(i))
    i+=1

i is now 0
i is now 1
i is now 2
i is now 3
i is now 4
i is now 5
i is now 6
i is now 7
i is now 8
i is now 9


<h1>Input and Output in Python</h1>
<p>Using Python we can read and open documents. This lets us work with external files</p>

drop

<h3>Writing to a text file</h3>
<p>You can also write a to a text file.</p>

In [0]:
item = input('Enter item: (‘q’ to quit) ')
shoppingList = [ ]
while item.lower() != 'q':
    shoppingList.append(item)
    item = input('Enter item: (‘q’ to quit) ')

print(shoppingList)


Enter item: (‘q’ to quit) orange
Enter item: (‘q’ to quit) q
['orange']


In [0]:
#Lets create a list with fish names
fishList = ["Red Zebra","OB Peacock","Venustus","Demansoni","Bumblebee Cichild"]
with open("fishText.txt","w") as fish_file:
    for fish in fishList:
        fish_file.write(fish + "\n")

In [0]:
textFile = open("fish.txt","r")

In [0]:
output = textFile.read()
print(output)
output

Snapper
Yellowtail
Grouper
Clownfish



'Snapper\nYellowtail\nGrouper\nClownfish\n'

In [0]:
textFile.read()

''

In [0]:
textFile.close()

<p>Noticed how we had to open then close the file. Similar to a word document when you open it you need to close it</p>

<p>What we did was open the file but still we do not see any data in the file.</p>

In [0]:
with open("fish.txt","r") as file:
    for line in file:
        print(line,end="")

Snapper
Yellowtail
Grouper
Clownfish


<h1>Functions</h1>
<p>Functions allow us to reuse code</p>

In [0]:
def print_name(name="Francisco"):
    print("Hello {0} how are you today".format(name))
    

In [0]:
print_name("Francisco")

Hello Francisco how are you today


Below we are going to show the benefits of using a function. Rather that alwasy having to write our code we can just execute a function

In [0]:
def find_word(word,list_name):
    for item in list_name:
        if item == word:
            position = list_name.index(word)
            return "The word {0} is the {1} element of the list".format(word,position)

In [0]:
sample_list = ['Sam','Dan','Nate','Andrew']

find_word("Sam",sample_list)

'The word Sam is the 0 element of the list'

You can add default parameters in case you or your user forget to pass a argument

In [0]:
print_name()

Hello Francisco how are you today


In [0]:
def find_word2(word,list_name):
    for item in list_name:
        if item == word:
            position = list_name.index(word)
            return word,position

w, p = find_word2('Nate',sample_list)
print("The word {} is the {} element of the list".format(w,p)) 


The word Nate is the 2 element of the list


<h3>Variable Scope</h3>
<p>Variables declared in a function can only be accesed by that functions. Where as global variables in the main block of code can be accessed by any function</p>

In [0]:
m_var = 10 # Declared outside the function global access
def sum_func(val1,val2):
    answer
    answer = val1 + val2 * m_var # answer is declared inside the function
    return(answer)

print(sum_func(2,1))
print(answer)

12
12


In [0]:
# Work arounds

x = 5

def update_list():
    global x
    x = 4
    print('Inside, x: {}'.format(x))
    
update_list()
print('Outside, x: {}'.format(x))

Inside, x: 4
Outside, x: 4


<h1>Getting Data and reading/writing data  drop</h1>
<p>In this section we will show how to grab data from the internet and also how to read/write that data</p>
<p>First we will import that requests module. The requests module is useful for sending HTTP requests</p>

In [0]:
import requests

requests_get = requests.get("http://api.open-notify.org/iss-now.json")
print(requests_get.text)

{"iss_position": {"latitude": "46.7336", "longitude": "84.7487"}, "message": "success", "timestamp": 1553096646}


<h2>Lets get the dataset for python</h2>
<p>Get the data from this URL: https://storage.googleapis.com/kaggle_data_datascience/train.csv</p>

In [0]:
import json

requests_get = requests.get("http://api.open-notify.org/iss-now.json")
print(requests_get.text)
print(requests_get.json())
print(json.dumps(requests_get.json(), sort_keys=True, indent=4))

{"iss_position": {"latitude": "47.3496", "longitude": "86.6510"}, "message": "success", "timestamp": 1553096669}
{'iss_position': {'latitude': '47.3496', 'longitude': '86.6510'}, 'message': 'success', 'timestamp': 1553096669}
{
    "iss_position": {
        "latitude": "47.3496",
        "longitude": "86.6510"
    },
    "message": "success",
    "timestamp": 1553096669
}


In [0]:
json.dump(requests_get.json(),open('sample.json','w'))
print(json.load(open('sample.json','r')))

{'iss_position': {'latitude': '47.3496', 'longitude': '86.6510'}, 'message': 'success', 'timestamp': 1553096669}


<h1>Pandas</h1>
<h2>Transforming and Indexing through data break out</h2>
<p>It is posssible to create dataframe from different datatypes we have seen before</p>

In [0]:
import pandas as pd # notice how pandas I am using a alias called pd. This is just a shorthand to help
import numpy as np

In [0]:
dframe_dict = pd.DataFrame({
    
    'Name': ['Salah','Kane','Aguero'],
    'Goals': [31,26,21],
    'Assists':[9,2,6],
    'Team':["LIV","TOT","MANC"]
})
dframe_dict.head()

Name  Goals  Assists  Team
0   Salah     31        9   LIV
1    Kane     26        2   TOT
2  Aguero     21        6  MANC

In [0]:
#From a tuple
player_tuples = [('Salah',9,31,'LIV'),
                 ('Kane',2,26,'TOT'),
                 ('Aguero',6,21,'MANC')
                ]

labels = ["Name","Goals","Assists","Team"]

dframe_list = pd.DataFrame(player_tuples,columns=labels)

In [0]:
dframe_list.head()

Name  Goals  Assists  Team
0   Salah      9       31   LIV
1    Kane      2       26   TOT
2  Aguero      6       21  MANC

In [0]:
#From a series
player_series = [
    
    pd.Series(["Salah",31,9,"LIV"],index=["Name","Goals","Assists","Team"]),
    pd.Series(["Kane",26,2,"TOT"],index=["Name","Goals","Assists","Team"]),
     pd.Series(["Aguero",21,6,"MANC"],index=["Name","Goals","Assists","Team"])
]
dframe_series = pd.DataFrame(player_series)

In [0]:
dframe_series.head()

Name  Goals  Assists  Team
0   Salah     31        9   LIV
1    Kane     26        2   TOT
2  Aguero     21        6  MANC

<h2>Reading Data</h2>
<p>We know we can read data by looping through files. And we know we can open files using the open function. 
However we can use use the pandas library to help us read data</p><br>
age: age in years<br>
sex: (1 = male; 0 = female)<br>
cp: chest pain type<br>
trestbps: resting blood pressure (in mm Hg on admission to the hospital)<br>
chol: serum cholestoral in mg/dl<br>
fbs: (fasting blood sugar > 120 mg/dl) (1 = true; 0 = false)<br>
restecg: resting electrocardiographic results<br>
thalach: maximum heart rate achieved<br>
exang: exercise induced angina (1 = yes; 0 = no)<br>
oldpeak: ST depression induced by exercise relative to rest<br>
slope: the slope of the peak exercise ST segment<br>
ca: number of major vessels (0-3) colored by flourosopy<br>
thal: 3 = normal; 6 = fixed defect; 7 = reversable defect<br>
target:1 or 0<br>

In [0]:
dframe = pd.read_csv('heart.csv')
dframe

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
5     57    1   0       140   192    0        1      148      0      0.4   
6     56    0   1       140   294    0        0      153      0      1.3   
7     44    1   1       120   263    0        1      173      0      0.0   
8     52    1   2       172   199    1        1      162      0      0.5   
9     57    1   2       150   168    0        1      174      0      1.6   
10    54    1   0       140   239    0        1      160      0      1.2   
11    48    0   2       130   275    0        1      139      0      0.2   
12    49    1   1       130   266    0        1      171      0      0.6   
13    64    1   3       110   211    0        0      144      1      1.8   
14    58    0   3       150   283    1        0      162      0      1.0   
15    50    0   2       120   219    0        1      158      0      1.6   
16    58    0   2       120   340    0        1      172      0      0.0   
17    66    0   3       150   226    0        1      114      0      2.6   
18    43    1   0       150   247    0        1      171      0      1.5   
19    69    0   3       140   239    0        1      151      0      1.8   
20    59    1   0       135   234    0        1      161      0      0.5   
21    44    1   2       130   233    0        1      179      1      0.4   
22    42    1   0       140   226    0        1      178      0      0.0   
23    61    1   2       150   243    1        1      137      1      1.0   
24    40    1   3       140   199    0        1      178      1      1.4   
25    71    0   1       160   302    0        1      162      0      0.4   
26    59    1   2       150   212    1        1      157      0      1.6   
27    51    1   2       110   175    0        1      123      0      0.6   
28    65    0   2       140   417    1        0      157      0      0.8   
29    53    1   2       130   197    1        0      152      0      1.2   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
273   58    1   0       100   234    0        1      156      0      0.1   
274   47    1   0       110   275    0        0      118      1      1.0   
275   52    1   0       125   212    0        1      168      0      1.0   
276   58    1   0       146   218    0        1      105      0      2.0   
277   57    1   1       124   261    0        1      141      0      0.3   
278   58    0   1       136   319    1        0      152      0      0.0   
279   61    1   0       138   166    0        0      125      1      3.6   
280   42    1   0       136   315    0        1      125      1      1.8   
281   52    1   0       128   204    1        1      156      1      1.0   
282   59    1   2       126   218    1        1      134      0      2.2   
283   40    1   0       152   223    0        1      181      0      0.0   
284   61    1   0       140   207    0        0      138      1      1.9   
285   46    1   0       140   311    0        1      120      1      1.8   
286   59    1   3       134   204    0        1      162      0      0.8   
287   57    1   1       154   232    0        0      164      0      0.0   
288   57    1   0       110   335    0        1      143      1      3.0   
289   55    0   0       128   205    0        2      130      1      2.0   
290   61    1   0       148   203    0        1      161      0      0.0   
291   58    1   0       114   318    0        2      140      0      4.4   
292   58    0   0       170   225    1        0      146      1      2.8   
293   67    1   2       152   212    0        0      

<h3>Working with dataframe</h3>
<p>Accessing dataframes by selecting specific columns and rows</p>

In [0]:
dframe.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [0]:
dframe.head(2)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   

   ca  thal  target  
0   0     1       1  
1   0     2       1

In [0]:
dframe.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [0]:
dframe['age']

0      63
1      37
2      41
3      56
4      57
5      57
6      56
7      44
8      52
9      57
10     54
11     48
12     49
13     64
14     58
15     50
16     58
17     66
18     43
19     69
20     59
21     44
22     42
23     61
24     40
25     71
26     59
27     51
28     65
29     53
       ..
273    58
274    47
275    52
276    58
277    57
278    58
279    61
280    42
281    52
282    59
283    40
284    61
285    46
286    59
287    57
288    57
289    55
290    61
291    58
292    58
293    67
294    44
295    63
296    63
297    59
298    57
299    45
300    68
301    57
302    57
Name: age, Length: 303, dtype: int64

In [0]:
dframe.age

0      63
1      37
2      41
3      56
4      57
5      57
6      56
7      44
8      52
9      57
10     54
11     48
12     49
13     64
14     58
15     50
16     58
17     66
18     43
19     69
20     59
21     44
22     42
23     61
24     40
25     71
26     59
27     51
28     65
29     53
       ..
273    58
274    47
275    52
276    58
277    57
278    58
279    61
280    42
281    52
282    59
283    40
284    61
285    46
286    59
287    57
288    57
289    55
290    61
291    58
292    58
293    67
294    44
295    63
296    63
297    59
298    57
299    45
300    68
301    57
302    57
Name: age, Length: 303, dtype: int64

In [0]:
#Accessing multiple columns
pd.DataFrame(dframe,columns = ['age', 'sex', 'cp'])

age  sex  cp
0     63    1   3
1     37    1   2
2     41    0   1
3     56    1   1
4     57    0   0
5     57    1   0
6     56    0   1
7     44    1   1
8     52    1   2
9     57    1   2
10    54    1   0
11    48    0   2
12    49    1   1
13    64    1   3
14    58    0   3
15    50    0   2
16    58    0   2
17    66    0   3
18    43    1   0
19    69    0   3
20    59    1   0
21    44    1   2
22    42    1   0
23    61    1   2
24    40    1   3
25    71    0   1
26    59    1   2
27    51    1   2
28    65    0   2
29    53    1   2
..   ...  ...  ..
273   58    1   0
274   47    1   0
275   52    1   0
276   58    1   0
277   57    1   1
278   58    0   1
279   61    1   0
280   42    1   0
281   52    1   0
282   59    1   2
283   40    1   0
284   61    1   0
285   46    1   0
286   59    1   3
287   57    1   1
288   57    1   0
289   55    0   0
290   61    1   0
291   58    1   0
292   58    0   0
293   67    1   2
294   44    1   0
295   63    1   0
296   63    0   0
297   59    1   0
298   57    0   0
299   45    1   3
300   68    1   0
301   57    1   0
302   57    0   1

[303 rows x 3 columns]

In [0]:
#Another way to access multiple columns
dframe[['age', 'sex', 'cp']]

age  sex  cp
0     63    1   3
1     37    1   2
2     41    0   1
3     56    1   1
4     57    0   0
5     57    1   0
6     56    0   1
7     44    1   1
8     52    1   2
9     57    1   2
10    54    1   0
11    48    0   2
12    49    1   1
13    64    1   3
14    58    0   3
15    50    0   2
16    58    0   2
17    66    0   3
18    43    1   0
19    69    0   3
20    59    1   0
21    44    1   2
22    42    1   0
23    61    1   2
24    40    1   3
25    71    0   1
26    59    1   2
27    51    1   2
28    65    0   2
29    53    1   2
..   ...  ...  ..
273   58    1   0
274   47    1   0
275   52    1   0
276   58    1   0
277   57    1   1
278   58    0   1
279   61    1   0
280   42    1   0
281   52    1   0
282   59    1   2
283   40    1   0
284   61    1   0
285   46    1   0
286   59    1   3
287   57    1   1
288   57    1   0
289   55    0   0
290   61    1   0
291   58    1   0
292   58    0   0
293   67    1   2
294   44    1   0
295   63    1   0
296   63    0   0
297   59    1   0
298   57    0   0
299   45    1   3
300   68    1   0
301   57    1   0
302   57    0   1

[303 rows x 3 columns]

<p>Accessing specific data based on logicial conditions</p>

In [0]:
dframe[(dframe["age"] < 30) & (dframe["target"] == 1)]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
72   29    1   1       130   204    0        0      202      0      0.0   

    slope  ca  thal  target  
72      2   0     2       1

In [0]:
dframe[np.logical_and(dframe["age"] < 30,dframe["target"] == 1)]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
72   29    1   1       130   204    0        0      202      0      0.0   

    slope  ca  thal  target  
72      2   0     2       1

In [0]:
dframe[(dframe["age"] < 30) | (dframe["age"] > 75)]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
72    29    1   1       130   204    0        0      202      0      0.0   
144   76    0   2       140   197    0        2      116      0      1.1   
238   77    1   0       125   304    0        0      162      1      0.0   

     slope  ca  thal  target  
72       2   0     2       1  
144      1   0     2       1  
238      2   3     2       0

In [0]:
dframe[np.logical_or(dframe["age"] < 30,dframe["age"] > 75)]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
72    29    1   1       130   204    0        0      202      0      0.0   
144   76    0   2       140   197    0        2      116      0      1.1   
238   77    1   0       125   304    0        0      162      1      0.0   

     slope  ca  thal  target  
72       2   0     2       1  
144      1   0     2       1  
238      2   3     2       0

In [0]:
#dframe[dframe["age"].isin(pd.Series([30,40,50]))]
dframe[dframe["age"].isin([30,40,50])]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
15    50    0   2       120   219    0        1      158      0      1.6   
24    40    1   3       140   199    0        1      178      1      1.4   
104   50    1   2       129   196    0        1      163      0      0.0   
108   50    0   1       120   244    0        1      162      0      1.1   
109   50    0   0       110   254    0        0      159      0      0.0   
175   40    1   0       110   167    0        0      114      1      2.0   
184   50    1   0       150   243    0        0      128      0      2.6   
188   50    1   2       140   233    0        1      163      0      0.6   
257   50    1   0       144   200    0        0      126      1      0.9   
283   40    1   0       152   223    0        1      181      0      0.0   

     slope  ca  thal  target  
15       1   0     2       1  
24       2   0     3       1  
104      2   0     2       1  
108      2   0     2       1  
109      2   0     2       1  
175      1   0     3       0  
184      1   0     3       0  
188      1   1     3       0  
257      1   0     3       0  
283      2   0     3       0

In [0]:
dframe.iloc[0:3]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1

In [0]:
dframe.iloc[0:3,:3]

age  sex  cp
0   63    1   3
1   37    1   2
2   41    0   1

In [0]:
dframe['participant'] = ['par{}'.format(identity) for identity in range(len(dframe))]
dframe

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
5     57    1   0       140   192    0        1      148      0      0.4   
6     56    0   1       140   294    0        0      153      0      1.3   
7     44    1   1       120   263    0        1      173      0      0.0   
8     52    1   2       172   199    1        1      162      0      0.5   
9     57    1   2       150   168    0        1      174      0      1.6   
10    54    1   0       140   239    0        1      160      0      1.2   
11    48    0   2       130   275    0        1      139      0      0.2   
12    49    1   1       130   266    0        1      171      0      0.6   
13    64    1   3       110   211    0        0      144      1      1.8   
14    58    0   3       150   283    1        0      162      0      1.0   
15    50    0   2       120   219    0        1      158      0      1.6   
16    58    0   2       120   340    0        1      172      0      0.0   
17    66    0   3       150   226    0        1      114      0      2.6   
18    43    1   0       150   247    0        1      171      0      1.5   
19    69    0   3       140   239    0        1      151      0      1.8   
20    59    1   0       135   234    0        1      161      0      0.5   
21    44    1   2       130   233    0        1      179      1      0.4   
22    42    1   0       140   226    0        1      178      0      0.0   
23    61    1   2       150   243    1        1      137      1      1.0   
24    40    1   3       140   199    0        1      178      1      1.4   
25    71    0   1       160   302    0        1      162      0      0.4   
26    59    1   2       150   212    1        1      157      0      1.6   
27    51    1   2       110   175    0        1      123      0      0.6   
28    65    0   2       140   417    1        0      157      0      0.8   
29    53    1   2       130   197    1        0      152      0      1.2   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
273   58    1   0       100   234    0        1      156      0      0.1   
274   47    1   0       110   275    0        0      118      1      1.0   
275   52    1   0       125   212    0        1      168      0      1.0   
276   58    1   0       146   218    0        1      105      0      2.0   
277   57    1   1       124   261    0        1      141      0      0.3   
278   58    0   1       136   319    1        0      152      0      0.0   
279   61    1   0       138   166    0        0      125      1      3.6   
280   42    1   0       136   315    0        1      125      1      1.8   
281   52    1   0       128   204    1        1      156      1      1.0   
282   59    1   2       126   218    1        1      134      0      2.2   
283   40    1   0       152   223    0        1      181      0      0.0   
284   61    1   0       140   207    0        0      138      1      1.9   
285   46    1   0       140   311    0        1      120      1      1.8   
286   59    1   3       134   204    0        1      162      0      0.8   
287   57    1   1       154   232    0        0      164      0      0.0   
288   57    1   0       110   335    0        1      143      1      3.0   
289   55    0   0       128   205    0        2      130      1      2.0   
290   61    1   0       148   203    0        1      161      0      0.0   
291   58    1   0       114   318    0        2      140      0      4.4   
292   58    0   0       170   225    1        0      146      1      2.8   
293   67    1   2       152   212    0        0      

In [0]:
dframe = dframe.set_index('participant')

In [0]:
dframe.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  \
participant                                                               
par0          63    1   3       145   233    1        0      150      0   
par1          37    1   2       130   250    0        1      187      0   
par2          41    0   1       130   204    0        0      172      0   
par3          56    1   1       120   236    0        1      178      0   
par4          57    0   0       120   354    0        1      163      1   

             oldpeak  slope  ca  thal  target  
participant                                    
par0             2.3      0   0     1       1  
par1             3.5      0   0     2       1  
par2             1.4      2   0     2       1  
par3             0.8      2   0     2       1  
par4             0.6      2   0     2       1

In [0]:
dframe.loc["par4"]

age          57.0
sex           0.0
cp            0.0
trestbps    120.0
chol        354.0
fbs           0.0
restecg       1.0
thalach     163.0
exang         1.0
oldpeak       0.6
slope         2.0
ca            0.0
thal          2.0
target        1.0
Name: par4, dtype: float64

In [0]:
dframe.loc[["par4","par99"],["age","sex"]]

age  sex
participant          
par4          57    0
par99         53    1

<p>We can add some more logic to select specific columns if they meet certain conditions</p>

In [0]:
dframe.reset_index(inplace=True)
dframe.head()

participant  age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  \
0        par0   63    1   3       145   233    1        0      150      0   
1        par1   37    1   2       130   250    0        1      187      0   
2        par2   41    0   1       130   204    0        0      172      0   
3        par3   56    1   1       120   236    0        1      178      0   
4        par4   57    0   0       120   354    0        1      163      1   

   oldpeak  slope  ca  thal  target  
0      2.3      0   0     1       1  
1      3.5      0   0     2       1  
2      1.4      2   0     2       1  
3      0.8      2   0     2       1  
4      0.6      2   0     2       1

In [0]:
dframe.loc[dframe["chol"] > 300, "age"].mean()

56.86046511627907

<h3>Adding columns</h3>

In [0]:
dframe["health"] = "True"

In [0]:
dframe.head()

participant  age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  \
0        par0   63    1   3       145   233    1        0      150      0   
1        par1   37    1   2       130   250    0        1      187      0   
2        par2   41    0   1       130   204    0        0      172      0   
3        par3   56    1   1       120   236    0        1      178      0   
4        par4   57    0   0       120   354    0        1      163      1   

   oldpeak  slope  ca  thal  target health  
0      2.3      0   0     1       1   True  
1      3.5      0   0     2       1   True  
2      1.4      2   0     2       1   True  
3      0.8      2   0     2       1   True  
4      0.6      2   0     2       1   True

In [0]:
dframe.head()

participant  age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  \
0        par0   63    1   3       145   233    1        0      150      0   
1        par1   37    1   2       130   250    0        1      187      0   
2        par2   41    0   1       130   204    0        0      172      0   
3        par3   56    1   1       120   236    0        1      178      0   
4        par4   57    0   0       120   354    0        1      163      1   

   oldpeak  slope  ca  thal  target health  
0      2.3      0   0     1       1   True  
1      3.5      0   0     2       1   True  
2      1.4      2   0     2       1   True  
3      0.8      2   0     2       1   True  
4      0.6      2   0     2       1   True

In [0]:
def decideHealth(age):
    age = int(age)
    if age >= 60:
        return 'old'
    
    elif age < 60 or age > 40:
        return 'Mid life'
    
    else:
        return 'Young'
    
dframe['health'] = dframe['age'].apply(decideHealth)
dframe

participant  age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  \
0          par0   63    1   3       145   233    1        0      150      0   
1          par1   37    1   2       130   250    0        1      187      0   
2          par2   41    0   1       130   204    0        0      172      0   
3          par3   56    1   1       120   236    0        1      178      0   
4          par4   57    0   0       120   354    0        1      163      1   
5          par5   57    1   0       140   192    0        1      148      0   
6          par6   56    0   1       140   294    0        0      153      0   
7          par7   44    1   1       120   263    0        1      173      0   
8          par8   52    1   2       172   199    1        1      162      0   
9          par9   57    1   2       150   168    0        1      174      0   
10        par10   54    1   0       140   239    0        1      160      0   
11        par11   48    0   2       130   275    0        1      139      0   
12        par12   49    1   1       130   266    0        1      171      0   
13        par13   64    1   3       110   211    0        0      144      1   
14        par14   58    0   3       150   283    1        0      162      0   
15        par15   50    0   2       120   219    0        1      158      0   
16        par16   58    0   2       120   340    0        1      172      0   
17        par17   66    0   3       150   226    0        1      114      0   
18        par18   43    1   0       150   247    0        1      171      0   
19        par19   69    0   3       140   239    0        1      151      0   
20        par20   59    1   0       135   234    0        1      161      0   
21        par21   44    1   2       130   233    0        1      179      1   
22        par22   42    1   0       140   226    0        1      178      0   
23        par23   61    1   2       150   243    1        1      137      1   
24        par24   40    1   3       140   199    0        1      178      1   
25        par25   71    0   1       160   302    0        1      162      0   
26        par26   59    1   2       150   212    1        1      157      0   
27        par27   51    1   2       110   175    0        1      123      0   
28        par28   65    0   2       140   417    1        0      157      0   
29        par29   53    1   2       130   197    1        0      152      0   
..          ...  ...  ...  ..       ...   ...  ...      ...      ...    ...   
273      par273   58    1   0       100   234    0        1      156      0   
274      par274   47    1   0       110   275    0        0      118      1   
275      par275   52    1   0       125   212    0        1      168      0   
276      par276   58    1   0       146   218    0        1      105      0   
277      par277   57    1   1       124   261    0        1      141      0   
278      par278   58    0   1       136   319    1        0      152      0   
279      par279   61    1   0       138   166    0        0      125      1   
280      par280   42    1   0       136   315    0        1      125      1   
281      par281   52    1   0       128   204    1        1      156      1   
282      par282   59    1   2       126   218    1        1      134      0   
283      par283   40    1   0       152   223    0        1      181      0   
284      par284   61    1   0       140   207    0        0      138      1   
285      par285   46    1   0       140   311    0        1      120      1   
286      par286   59    1   3       134   204    0        1      162      0   
287      par287   57    1   1       154   232    0        0      164      0   
288      par288   57    1   0       110   335    0        1      143      1   
289      par289   55    0   0       128   205    0        2      130      1   
290      par290   61    1   0       148   203    0        1      161      0   
291      par291   58    1   0       114   318    0    

<h3>Dropping Columns</h3>

In [0]:
dframe.drop(["health"],axis=1,inplace = True)

<h3>Merge</h3>

In [0]:
dframe1 = pd.DataFrame({
    
    'key1': ['A','B','B','C','C'],
    'key2': ['Y','Y','Z','Z','Z'],
    'series1':range(5)
})

dframe2 = pd.DataFrame({
    
    'key1': ['B','C','D','D'],
    'key2': ['X','Z','Y','Z'],
    'series2':range(4)
})


In [0]:
print(dframe1)
print()
print(dframe2)

  key1 key2  series1
0    A    Y        0
1    B    Y        1
2    B    Z        2
3    C    Z        3
4    C    Z        4

  key1 key2  series2
0    B    X        0
1    C    Z        1
2    D    Y        2
3    D    Z        3


In [0]:
pd.merge(dframe1,dframe2)

key1 key2  series1  series2
0    C    Z        3        1
1    C    Z        4        1

In [0]:
#Merging on a specific key
pd.merge(dframe1,dframe2,on='key1')

key1 key2_x  series1 key2_y  series2
0    B      Y        1      X        0
1    B      Z        2      X        0
2    C      Z        3      Z        1
3    C      Z        4      Z        1

In [0]:
dframe1.merge(dframe2,on='key1')

key1 key2_x  series1 key2_y  series2
0    B      Y        1      X        0
1    B      Z        2      X        0
2    C      Z        3      Z        1
3    C      Z        4      Z        1

In [0]:
pd.merge(dframe1,dframe2,how='left')

key1 key2  series1  series2
0    A    Y        0      NaN
1    B    Y        1      NaN
2    B    Z        2      NaN
3    C    Z        3      1.0
4    C    Z        4      1.0

In [0]:
dframe1.merge(dframe2,how='left')

key1 key2  series1  series2
0    A    Y        0      NaN
1    B    Y        1      NaN
2    B    Z        2      NaN
3    C    Z        3      1.0
4    C    Z        4      1.0

<h3>Combine</h3>

In [0]:
import numpy as np

In [0]:
nan = np.nan

In [0]:
dframe1 = pd.DataFrame({
    
    'A':[10,11,nan,12,13],
    'B':[14,nan,nan,15,16]
    
})

dframe2 = pd.DataFrame({
    
    'A':[21,nan,22,nan],
    'B':[23,24,nan,nan],
    'C':[nan,25,26,27]
})

In [0]:
dframe1

A     B
0  10.0  14.0
1  11.0   NaN
2   NaN   NaN
3  12.0  15.0
4  13.0  16.0

In [0]:
dframe2

A     B     C
0  21.0  23.0   NaN
1   NaN  24.0  25.0
2  22.0   NaN  26.0
3   NaN   NaN  27.0

In [0]:
dframe1.combine_first(dframe2)

A     B     C
0  10.0  14.0   NaN
1  11.0  24.0  25.0
2  22.0   NaN  26.0
3  12.0  15.0  27.0
4  13.0  16.0   NaN

<h3>Concatenate</h3>

In [0]:
dframe1 = pd.DataFrame({
    'A': ['A1','A2','A3','A4','A5'],
    'B': ['B1','B2','B3','B4','B5']
})

dframe2 = pd.DataFrame({
    'A': ['A6','A7','A8','A9'],
    'B': ['B6','B7','B8','B9'],
    'C': ['C6','C7','C8','C9']
})

In [0]:
dframe1

A   B
0  A1  B1
1  A2  B2
2  A3  B3
3  A4  B4
4  A5  B5

In [0]:
dframe2

A   B   C
0  A6  B6  C6
1  A7  B7  C7
2  A8  B8  C8
3  A9  B9  C9

In [0]:
frames = [dframe1,dframe2]
pd.concat(frames,ignore_index=True)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


A   B    C
0  A1  B1  NaN
1  A2  B2  NaN
2  A3  B3  NaN
3  A4  B4  NaN
4  A5  B5  NaN
5  A6  B6   C6
6  A7  B7   C7
7  A8  B8   C8
8  A9  B9   C9

In [0]:
dframe1.append(dframe2,ignore_index=True)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)


A   B    C
0  A1  B1  NaN
1  A2  B2  NaN
2  A3  B3  NaN
3  A4  B4  NaN
4  A5  B5  NaN
5  A6  B6   C6
6  A7  B7   C7
7  A8  B8   C8
8  A9  B9   C9

### Transpose, groupby etc

In [0]:
dframe.T

0     1     2     3     4     5     6     7     8     9    \
participant  par0  par1  par2  par3  par4  par5  par6  par7  par8  par9   
age            63    37    41    56    57    57    56    44    52    57   
sex             1     1     0     1     0     1     0     1     1     1   
cp              3     2     1     1     0     0     1     1     2     2   
trestbps      145   130   130   120   120   140   140   120   172   150   
chol          233   250   204   236   354   192   294   263   199   168   
fbs             1     0     0     0     0     0     0     0     1     0   
restecg         0     1     0     1     1     1     0     1     1     1   
thalach       150   187   172   178   163   148   153   173   162   174   
exang           0     0     0     0     1     0     0     0     0     0   
oldpeak       2.3   3.5   1.4   0.8   0.6   0.4   1.3     0   0.5   1.6   
slope           0     0     2     2     2     1     1     2     2     2   
ca              0     0     0     0     0     0     0     0     0     0   
thal            1     2     2     2     2     1     2     3     3     2   
target          1     1     1     1     1     1     1     1     1     1   

              ...       293     294     295     296     297     298     299  \
participant   ...    par293  par294  par295  par296  par297  par298  par299   
age           ...        67      44      63      63      59      57      45   
sex           ...         1       1       1       0       1       0       1   
cp            ...         2       0       0       0       0       0       3   
trestbps      ...       152     120     140     124     164     140     110   
chol          ...       212     169     187     197     176     241     264   
fbs           ...         0       0       0       0       1       0       0   
restecg       ...         0       1       0       1       0       1       1   
thalach       ...       150     144     144     136      90     123     132   
exang         ...         0       1       1       1       0       1       0   
oldpeak       ...       0.8     2.8       4       0       1     0.2     1.2   
slope         ...         1       0       2       1       1       1       1   
ca            ...         0       0       2       0       2       0       0   
thal          ...         3       1       3       2       1       3       3   
target        ...         0       0       0       0       0       0       0   

                300     301     302  
participant  par300  par301  par302  
age              68      57      57  
sex               1       1       0  
cp                0       0       1  
trestbps        144     130     130  
chol            193     131     236  
fbs               1       0       0  
restecg           1       1       0  
thalach         141     115     174  
exang             0       1       0  
oldpeak         3.4     1.2       0  
slope             1       1       1  
ca                2       1       1  
thal              3       3       2  
target            0       0       0  

[15 rows x 303 columns]

In [0]:
dframe3 = dframe.groupby(['sex','target']).agg({'age':'mean'})
dframe3

age
sex target           
0   0       59.041667
    1       54.555556
1   0       56.087719
    1       50.903226

In [0]:
dframe3.unstack(1)

age           
target          0          1
sex                         
0       59.041667  54.555556
1       56.087719  50.903226

In [0]:
dframe3.stack(0)

sex  target     
0    0       age    59.041667
     1       age    54.555556
1    0       age    56.087719
     1       age    50.903226
dtype: float64

In [0]:
dframe3.reset_index()

sex  target        age
0    0       0  59.041667
1    0       1  54.555556
2    1       0  56.087719
3    1       1  50.903226

<h1>Investigating</h1>

<p>It is now time to investigate the data</p>

In [0]:
dframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 15 columns):
participant    303 non-null object
age            303 non-null int64
sex            303 non-null int64
cp             303 non-null int64
trestbps       303 non-null int64
chol           303 non-null int64
fbs            303 non-null int64
restecg        303 non-null int64
thalach        303 non-null int64
exang          303 non-null int64
oldpeak        303 non-null float64
slope          303 non-null int64
ca             303 non-null int64
thal           303 non-null int64
target         303 non-null int64
dtypes: float64(1), int64(13), object(1)
memory usage: 35.6+ KB


In [0]:
dframe.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [0]:
dframe.corr()

age       sex        cp  trestbps      chol       fbs  \
age       1.000000 -0.098447 -0.068653  0.279351  0.213678  0.121308   
sex      -0.098447  1.000000 -0.049353 -0.056769 -0.197912  0.045032   
cp       -0.068653 -0.049353  1.000000  0.047608 -0.076904  0.094444   
trestbps  0.279351 -0.056769  0.047608  1.000000  0.123174  0.177531   
chol      0.213678 -0.197912 -0.076904  0.123174  1.000000  0.013294   
fbs       0.121308  0.045032  0.094444  0.177531  0.013294  1.000000   
restecg  -0.116211 -0.058196  0.044421 -0.114103 -0.151040 -0.084189   
thalach  -0.398522 -0.044020  0.295762 -0.046698 -0.009940 -0.008567   
exang     0.096801  0.141664 -0.394280  0.067616  0.067023  0.025665   
oldpeak   0.210013  0.096093 -0.149230  0.193216  0.053952  0.005747   
slope    -0.168814 -0.030711  0.119717 -0.121475 -0.004038 -0.059894   
ca        0.276326  0.118261 -0.181053  0.101389  0.070511  0.137979   
thal      0.068001  0.210041 -0.161736  0.062210  0.098803 -0.032019   
target   -0.225439 -0.280937  0.433798 -0.144931 -0.085239 -0.028046   

           restecg   thalach     exang   oldpeak     slope        ca  \
age      -0.116211 -0.398522  0.096801  0.210013 -0.168814  0.276326   
sex      -0.058196 -0.044020  0.141664  0.096093 -0.030711  0.118261   
cp        0.044421  0.295762 -0.394280 -0.149230  0.119717 -0.181053   
trestbps -0.114103 -0.046698  0.067616  0.193216 -0.121475  0.101389   
chol     -0.151040 -0.009940  0.067023  0.053952 -0.004038  0.070511   
fbs      -0.084189 -0.008567  0.025665  0.005747 -0.059894  0.137979   
restecg   1.000000  0.044123 -0.070733 -0.058770  0.093045 -0.072042   
thalach   0.044123  1.000000 -0.378812 -0.344187  0.386784 -0.213177   
exang    -0.070733 -0.378812  1.000000  0.288223 -0.257748  0.115739   
oldpeak  -0.058770 -0.344187  0.288223  1.000000 -0.577537  0.222682   
slope     0.093045  0.386784 -0.257748 -0.577537  1.000000 -0.080155   
ca       -0.072042 -0.213177  0.115739  0.222682 -0.080155  1.000000   
thal     -0.011981 -0.096439  0.206754  0.210244 -0.104764  0.151832   
target    0.137230  0.421741 -0.436757 -0.430696  0.345877 -0.391724   

              thal    target  
age       0.068001 -0.225439  
sex       0.210041 -0.280937  
cp       -0.161736  0.433798  
trestbps  0.062210 -0.144931  
chol      0.098803 -0.085239  
fbs      -0.032019 -0.028046  
restecg  -0.011981  0.137230  
thalach  -0.096439  0.421741  
exang     0.206754 -0.436757  
oldpeak   0.210244 -0.430696  
slope    -0.104764  0.345877  
ca        0.151832 -0.391724  
thal      1.000000 -0.344029  
target   -0.344029  1.000000

In [0]:
corr_matrix = dframe.corr()
corr_matrix["age"].sort_values(ascending=False)

age         1.000000
trestbps    0.279351
ca          0.276326
chol        0.213678
oldpeak     0.210013
fbs         0.121308
exang       0.096801
thal        0.068001
cp         -0.068653
sex        -0.098447
restecg    -0.116211
slope      -0.168814
target     -0.225439
thalach    -0.398522
Name: age, dtype: float64

<h3>Feature Engineering</h3>
<p>Feature engineering allows us to create new feature that may help us build our model.</p>
<p>If we look at our data one key thing we are missing is the total area size</p>

In [0]:
dframe['age_chol'] = dframe['age'] + dframe['chol']
dframe


participant  age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  \
0          par0   63    1   3       145   233    1        0      150      0   
1          par1   37    1   2       130   250    0        1      187      0   
2          par2   41    0   1       130   204    0        0      172      0   
3          par3   56    1   1       120   236    0        1      178      0   
4          par4   57    0   0       120   354    0        1      163      1   
5          par5   57    1   0       140   192    0        1      148      0   
6          par6   56    0   1       140   294    0        0      153      0   
7          par7   44    1   1       120   263    0        1      173      0   
8          par8   52    1   2       172   199    1        1      162      0   
9          par9   57    1   2       150   168    0        1      174      0   
10        par10   54    1   0       140   239    0        1      160      0   
11        par11   48    0   2       130   275    0        1      139      0   
12        par12   49    1   1       130   266    0        1      171      0   
13        par13   64    1   3       110   211    0        0      144      1   
14        par14   58    0   3       150   283    1        0      162      0   
15        par15   50    0   2       120   219    0        1      158      0   
16        par16   58    0   2       120   340    0        1      172      0   
17        par17   66    0   3       150   226    0        1      114      0   
18        par18   43    1   0       150   247    0        1      171      0   
19        par19   69    0   3       140   239    0        1      151      0   
20        par20   59    1   0       135   234    0        1      161      0   
21        par21   44    1   2       130   233    0        1      179      1   
22        par22   42    1   0       140   226    0        1      178      0   
23        par23   61    1   2       150   243    1        1      137      1   
24        par24   40    1   3       140   199    0        1      178      1   
25        par25   71    0   1       160   302    0        1      162      0   
26        par26   59    1   2       150   212    1        1      157      0   
27        par27   51    1   2       110   175    0        1      123      0   
28        par28   65    0   2       140   417    1        0      157      0   
29        par29   53    1   2       130   197    1        0      152      0   
..          ...  ...  ...  ..       ...   ...  ...      ...      ...    ...   
273      par273   58    1   0       100   234    0        1      156      0   
274      par274   47    1   0       110   275    0        0      118      1   
275      par275   52    1   0       125   212    0        1      168      0   
276      par276   58    1   0       146   218    0        1      105      0   
277      par277   57    1   1       124   261    0        1      141      0   
278      par278   58    0   1       136   319    1        0      152      0   
279      par279   61    1   0       138   166    0        0      125      1   
280      par280   42    1   0       136   315    0        1      125      1   
281      par281   52    1   0       128   204    1        1      156      1   
282      par282   59    1   2       126   218    1        1      134      0   
283      par283   40    1   0       152   223    0        1      181      0   
284      par284   61    1   0       140   207    0        0      138      1   
285      par285   46    1   0       140   311    0        1      120      1   
286      par286   59    1   3       134   204    0        1      162      0   
287      par287   57    1   1       154   232    0        0      164      0   
288      par288   57    1   0       110   335    0        1      143      1   
289      par289   55    0   0       128   205    0        2      130      1   
290      par290   61    1   0       148   203    0        1      161      0   
291      par291   58    1   0       114   318    0    

Dealing with nans

In [0]:
import random

dframe['someNans'] = [np.nan if x % 2 == 0 else random.randint(1,100) for x in range(len(dframe))]
dframe.head()

participant  age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  \
0        par0   63    1   3       145   233    1        0      150      0   
1        par1   37    1   2       130   250    0        1      187      0   
2        par2   41    0   1       130   204    0        0      172      0   
3        par3   56    1   1       120   236    0        1      178      0   
4        par4   57    0   0       120   354    0        1      163      1   

   oldpeak  slope  ca  thal  target  age_chol  someNans  
0      2.3      0   0     1       1       296       NaN  
1      3.5      0   0     2       1       287      23.0  
2      1.4      2   0     2       1       245       NaN  
3      0.8      2   0     2       1       292      10.0  
4      0.6      2   0     2       1       411       NaN

In [0]:
dframe.isnull().any()

participant    False
age            False
sex            False
cp             False
trestbps       False
chol           False
fbs            False
restecg        False
thalach        False
exang          False
oldpeak        False
slope          False
ca             False
thal           False
target         False
age_chol       False
someNans        True
dtype: bool

In [0]:
dframe4 = dframe.copy()
dframe4['someNans'] = dframe4['someNans'].fillna(0)
dframe4.head()

participant  age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  \
0        par0   63    1   3       145   233    1        0      150      0   
1        par1   37    1   2       130   250    0        1      187      0   
2        par2   41    0   1       130   204    0        0      172      0   
3        par3   56    1   1       120   236    0        1      178      0   
4        par4   57    0   0       120   354    0        1      163      1   

   oldpeak  slope  ca  thal  target  age_chol  someNans  
0      2.3      0   0     1       1       296       0.0  
1      3.5      0   0     2       1       287      23.0  
2      1.4      2   0     2       1       245       0.0  
3      0.8      2   0     2       1       292      10.0  
4      0.6      2   0     2       1       411       0.0

In [0]:
dframe4 = dframe.copy()
dframe4['someNans'] = dframe4['someNans'].fillna(dframe4['someNans'].mean())
dframe4.head()

participant  age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  \
0        par0   63    1   3       145   233    1        0      150      0   
1        par1   37    1   2       130   250    0        1      187      0   
2        par2   41    0   1       130   204    0        0      172      0   
3        par3   56    1   1       120   236    0        1      178      0   
4        par4   57    0   0       120   354    0        1      163      1   

   oldpeak  slope  ca  thal  target  age_chol   someNans  
0      2.3      0   0     1       1       296  52.509934  
1      3.5      0   0     2       1       287  23.000000  
2      1.4      2   0     2       1       245  52.509934  
3      0.8      2   0     2       1       292  10.000000  
4      0.6      2   0     2       1       411  52.509934

### Saving the dataframe

In [0]:
#dframe.to_json('sample.json')
#dframe.to_excel('sample.xlsx')
dframe.to_csv('sample.csv')

## NumPy
NumPy arrays treat everything like vectors and matrices. A 2D numpy array can be thought of as a pandas dataframe. <br> Operations in numpy tend to be faster than pandas.
<br> To explain dims discuss markov chain

In [0]:
import numpy as np
x = [1,2,3,4,5,6,7,8,9,10,11,12]
x = np.array(x)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [0]:
type(x)

numpy.ndarray

In [0]:
print(np.expand_dims(x,axis=0))
print()
print(np.expand_dims(x,axis=1))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


Reshape up

In [0]:
x.shape

(12,)

In [0]:
x.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Reshape down

In [0]:
y = np.array([[[x for x in range(10)],[x for x in range(10)],[x for x in range(10)]],[[x for x in range(10)],[x for x in range(10)],[x for x in range(10)]]])
y

array([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [0]:
y.shape

(2, 3, 10)

In [0]:
print(y.reshape(15,4))
print()
print(y.reshape(60))

[[0 1 2 3]
 [4 5 6 7]
 [8 9 0 1]
 [2 3 4 5]
 [6 7 8 9]
 [0 1 2 3]
 [4 5 6 7]
 [8 9 0 1]
 [2 3 4 5]
 [6 7 8 9]
 [0 1 2 3]
 [4 5 6 7]
 [8 9 0 1]
 [2 3 4 5]
 [6 7 8 9]]

[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6
 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]


From pandas to numpy

In [0]:
dnumpy = dframe.values
dnumpy

array([['par0', 63, 1, ..., 1, 296, nan],
       ['par1', 37, 1, ..., 1, 287, 23.0],
       ['par2', 41, 0, ..., 1, 245, nan],
       ...,
       ['par300', 68, 1, ..., 0, 261, nan],
       ['par301', 57, 1, ..., 0, 188, 67.0],
       ['par302', 57, 0, ..., 0, 293, nan]], dtype=object)

In [0]:
pd.DataFrame(dnumpy)

0   1  2  3    4    5  6  7    8  9    10 11 12 13 14   15   16
0      par0  63  1  3  145  233  1  0  150  0  2.3  0  0  1  1  296  NaN
1      par1  37  1  2  130  250  0  1  187  0  3.5  0  0  2  1  287   23
2      par2  41  0  1  130  204  0  0  172  0  1.4  2  0  2  1  245  NaN
3      par3  56  1  1  120  236  0  1  178  0  0.8  2  0  2  1  292   10
4      par4  57  0  0  120  354  0  1  163  1  0.6  2  0  2  1  411  NaN
5      par5  57  1  0  140  192  0  1  148  0  0.4  1  0  1  1  249   62
6      par6  56  0  1  140  294  0  0  153  0  1.3  1  0  2  1  350  NaN
7      par7  44  1  1  120  263  0  1  173  0    0  2  0  3  1  307   33
8      par8  52  1  2  172  199  1  1  162  0  0.5  2  0  3  1  251  NaN
9      par9  57  1  2  150  168  0  1  174  0  1.6  2  0  2  1  225   23
10    par10  54  1  0  140  239  0  1  160  0  1.2  2  0  2  1  293  NaN
11    par11  48  0  2  130  275  0  1  139  0  0.2  2  0  2  1  323   14
12    par12  49  1  1  130  266  0  1  171  0  0.6  2  0  2  1  315  NaN
13    par13  64  1  3  110  211  0  0  144  1  1.8  1  0  2  1  275   99
14    par14  58  0  3  150  283  1  0  162  0    1  2  0  2  1  341  NaN
15    par15  50  0  2  120  219  0  1  158  0  1.6  1  0  2  1  269   34
16    par16  58  0  2  120  340  0  1  172  0    0  2  0  2  1  398  NaN
17    par17  66  0  3  150  226  0  1  114  0  2.6  0  0  2  1  292   93
18    par18  43  1  0  150  247  0  1  171  0  1.5  2  0  2  1  290  NaN
19    par19  69  0  3  140  239  0  1  151  0  1.8  2  2  2  1  308    4
20    par20  59  1  0  135  234  0  1  161  0  0.5  1  0  3  1  293  NaN
21    par21  44  1  2  130  233  0  1  179  1  0.4  2  0  2  1  277   97
22    par22  42  1  0  140  226  0  1  178  0    0  2  0  2  1  268  NaN
23    par23  61  1  2  150  243  1  1  137  1    1  1  0  2  1  304   65
24    par24  40  1  3  140  199  0  1  178  1  1.4  2  0  3  1  239  NaN
25    par25  71  0  1  160  302  0  1  162  0  0.4  2  2  2  1  373   78
26    par26  59  1  2  150  212  1  1  157  0  1.6  2  0  2  1  271  NaN
27    par27  51  1  2  110  175  0  1  123  0  0.6  2  0  2  1  226   18
28    par28  65  0  2  140  417  1  0  157  0  0.8  2  1  2  1  482  NaN
29    par29  53  1  2  130  197  1  0  152  0  1.2  0  0  2  1  250   25
..      ...  .. .. ..  ...  ... .. ..  ... ..  ... .. .. .. ..  ...  ...
273  par273  58  1  0  100  234  0  1  156  0  0.1  2  1  3  0  292   32
274  par274  47  1  0  110  275  0  0  118  1    1  1  1  2  0  322  NaN
275  par275  52  1  0  125  212  0  1  168  0    1  2  2  3  0  264   74
276  par276  58  1  0  146  218  0  1  105  0    2  1  1  3  0  276  NaN
277  par277  57  1  1  124  261  0  1  141  0  0.3  2  0  3  0  318   48
278  par278  58  0  1  136  319  1  0  152  0    0  2  2  2  0  377  NaN
279  par279  61  1  0  138  166  0  0  125  1  3.6  1  1  2  0  227   67
280  par280  42  1  0  136  315  0  1  125  1  1.8  1  0  1  0  357  NaN
281  par281  52  1  0  128  204  1  1  156  1    1  1  0  0  0  256   62
282  par282  59  1  2  126  218  1  1  134  0  2.2  1  1  1  0  277  NaN
283  par283  40  1  0  152  223  0  1  181  0    0  2  0  3  0  263    2
284  par284  61  1  0  140  207  0  0  138  1  1.9  2  1  3  0  268  NaN
285  par285  46  1  0  140  311  0  1  120  1  1.8  1  2  3  0  357   32
286  par286  59  1  3  134  204  0  1  162  0  0.8  2  2  2  0  263  NaN
287  par287  57  1  1  154  232  0  0  164  0    0  2  1  2  0  289   49
288  par288  57  1  0  110  335  0  1  143  1    3  1  1  3  0  392  NaN
289  par289  55  0  0  128  205  0  2  130  1    2  1  1  3  0  260   38
290  par290  61  1  0  148  203  0  1  161  0    0  2  1  3  0  264  NaN
291  par291  58  1  0  114  318  0  2  140  0  4.4  0  3  1  0  376   19
292  par292  58  0  0  170  225  1  0  146  1  2.8  1  2  1  0  283  NaN
293  par293  67  1  2  152  212  0  0  150  0  0.8  1  0  3  0  279   28
294  par294  44  1  0  120  169  0  1  144  1  2.8  0  0  1  0  213  NaN
295  par295  63  1  0  140  187  0  0  144  1    4  2  2  3  0  250

In [0]:
dnumpy.shape

In [0]:
print(np.expand_dims(dnumpy,axis=1))
np.expand_dims(dnumpy,axis=1).shape

Accessing columns and rows

In [0]:
dnumpy[:,0] # Columns

In [0]:
dnumpy[0:5,:] # Columns

In [0]:
dnumpy[0:5,[0,3]]

In [0]:
dnumpy[dnumpy[:,1] > 30]

In [0]:
#dnumpy[np.logical_and(dnumpy[:,1] > 30, dnumpy[:,-1] ==1)]
dnumpy[np.logical_and(dnumpy[:,1] > 30, dnumpy[:,-1] ==1)]

In [0]:
n, m = dnumpy.shape

In [0]:
col = np.array([[x] for x in range(n)]) 
np.append(dnumpy,col,1) # Add column

In [0]:
col = np.array([[x for x in range(m)]])
np.append(dnumpy,col,0) # Add row

In [0]:
dnumpy2 = dnumpy.copy()
dnumpy2[:,1] = dnumpy[:,1] + 5
dnumpy2

In [0]:
dnumpy2[:,1] = dnumpy2[:,1] - dnumpy[:,1]
dnumpy2

In [0]:
dnumpy2[:,1] = dnumpy2[:,1] / dnumpy[:,1]
dnumpy2